-- GearPath
-- Data/GearPath_Data.lua - BiS tables
-- AUTO-GENERATED by companion app. Do not edit manually.
-- Run: cd companion && go run . generate
-- Last generated: 2026-04-15 22:19:50

GearPath.BiSData = {}

GearPath.BiSData["SHAMAN"] = GearPath.BiSData["SHAMAN"] or {}
GearPath.BiSData["SHAMAN"]["Elemental"] = {
    -- Season: Midnight S1 | Updated: 2026-04-15

    [1] = {
        itemID     = 249979,
        itemName   = "Locus of the Primal Core",
        slotID     = 1,
        source     = "Voidspire",
        sourceType = "RAID",
        sourceName = "The Voidspire",
        bossName   = "Vaelgor the Fallen",
        ilvl       = 252,
        priority   = 9,
        isTier     = true,
    },

    [2] = {
        itemID     = 250247,
        itemName   = "Amulet of the Abyssal Hymn",
        slotID     = 2,
        source     = "MarchOnQueldanas",
        sourceType = "RAID",
        sourceName = "March on Quel'Danas",
        bossName   = "Midnight Falls",
        ilvl       = 252,
        priority   = 8,
        isTier     = false,
    },

    [3] = {
        itemID     = 249980,
        itemName   = "Tempests of the Primal Core",
        slotID     = 3,
        source     = "Voidspire",
        sourceType = "RAID",
        sourceName = "The Voidspire",
        bossName   = "Council of Silvermoon",
        ilvl       = 252,
        priority   = 9,
        isTier     = true,
    },

    [5] = {
        itemID     = 249982,
        itemName   = "Embrace of the Primal Core",
        slotID     = 5,
        source     = "Voidspire",
        sourceType = "RAID",
        sourceName = "The Voidspire",
        bossName   = "Xal'atath",
        ilvl       = 252,
        priority   = 9,
        isTier     = true,
    },

    [6] = {
        itemID     = 244611,
        itemName   = "World Tender's Barkclasp",
        slotID     = 6,
        source     = "Crafted",
        sourceType = "CRAFTED",
        sourceName = "Crafted",
        bossName   = nil,
        ilvl       = 265,
        priority   = 7,
        isTier     = false,
    },

    [7] = {
        itemID     = 251215,
        itemName   = "Greaves of the Divine Guile",
        slotID     = 7,
        source     = "MarchOnQueldanas",
        sourceType = "RAID",
        sourceName = "March on Quel'Danas",
        bossName   = nil,
        ilvl       = 252,
        priority   = 7,
        isTier     = false,
    },

    [8] = {
        itemID     = 244610,
        itemName   = "World Tender's Rootslippers",
        slotID     = 8,
        source     = "Crafted",
        sourceType = "CRAFTED",
        sourceName = "Crafted",
        bossName   = nil,
        ilvl       = 265,
        priority   = 7,
        isTier     = false,
    },

    [9] = {
        itemID     = 249304,
        itemName   = "Fallen King's Cuffs",
        slotID     = 9,
        source     = "MarchOnQueldanas",
        sourceType = "RAID",
        sourceName = "March on Quel'Danas",
        bossName   = nil,
        ilvl       = 252,
        priority   = 6,
        isTier     = false,
    },

    [10] = {
        itemID     = 249983,
        itemName   = "Earthgrips of the Primal Core",
        slotID     = 10,
        source     = "Voidspire",
        sourceType = "RAID",
        sourceName = "The Voidspire",
        bossName   = nil,
        ilvl       = 252,
        priority   = 9,
        isTier     = true,
    },

    [11] = {
        itemID     = 193708,
        itemName   = "Platinum Star Band",
        slotID     = 11,
        source     = "AlgetharAcademy",
        sourceType = "DUNGEON",
        sourceName = "Algeth'ar Academy",
        bossName   = nil,
        ilvl       = 252,
        priority   = 7,
        isTier     = false,
    },

    [12] = {
        itemID     = 249919,
        itemName   = "Sin'dorei Band of Hope",
        slotID     = 12,
        source     = "MarchOnQueldanas",
        sourceType = "RAID",
        sourceName = "March on Quel'Danas",
        bossName   = nil,
        ilvl       = 252,
        priority   = 7,
        isTier     = false,
    },

    [13] = {
        itemID     = 249343,
        itemName   = "Gaze of the Alnseer",
        slotID     = 13,
        source     = "Dreamrift",
        sourceType = "RAID",
        sourceName = "Dreamrift",
        bossName   = "Chimaerus",
        ilvl       = 252,
        priority   = 10,
        isTier     = false,
    },

    [14] = {
        itemID     = 250144,
        itemName   = "Emberwing Feather",
        slotID     = 14,
        source     = "WindrunnerSpire",
        sourceType = "DUNGEON",
        sourceName = "Windrunner Spire",
        bossName   = "Emberdawn",
        ilvl       = 252,
        priority   = 10,
        isTier     = false,
    },

    [15] = {
        itemID     = 249974,
        itemName   = "Guardian of the Primal Core",
        slotID     = 15,
        source     = "Voidspire",
        sourceType = "RAID",
        sourceName = "The Voidspire",
        bossName   = nil,
        ilvl       = 252,
        priority   = 6,
        isTier     = false,
    },

    [16] = {
        itemID     = 251083,
        itemName   = "Excavating Cudgel",
        slotID     = 16,
        source     = "Crafted",
        sourceType = "CRAFTED",
        sourceName = "Crafted",
        bossName   = nil,
        ilvl       = 265,
        priority   = 10,
        isTier     = false,
    },

    [17] = {
        itemID     = 251105,
        itemName   = "Ward of the Spellbreaker",
        slotID     = 17,
        source     = "MagistersTerrace",
        sourceType = "DUNGEON",
        sourceName = "Magisters' Terrace",
        bossName   = "Seranel Sunlash",
        ilvl       = 252,
        priority   = 9,
        isTier     = false,
    },

}
