-- GearPath
-- Data/GearPath_Stats.lua - Stat priorities, gems, enchants, consumables
-- AUTO-GENERATED by companion app. Do not edit manually.
-- Run: cd companion && go run . generate-guide
-- Last generated: 2026-04-26 10:57:26
--
-- Consumables for Blood DK (Deathbringer vs San'layn) and Enhancement Shaman
-- (Stormbringer vs Totemic) are approximate per hero talent — both hero talents
-- see the first-mentioned recommendation on the page. See Icy Veins for
-- hero-specific consumable differences. Per-hero consumable parsing deferred
-- to v0.3.1+.
--
-- Holy Paladin Lightsmith weapon oil: both hero talents show Thalassian Phoenix
-- Oil. Lightsmith users who use Rite of Sanctification may not need it.

GearPath.GuideData = {}

GearPath.GuideData["DEATHKNIGHT"] = GearPath.GuideData["DEATHKNIGHT"] or {}
GearPath.GuideData["DEATHKNIGHT"]["Blood"] = {}

-- DEATHKNIGHT Blood [Deathbringer] | Updated: 2026-04-26
GearPath.GuideData["DEATHKNIGHT"]["Blood"]["Deathbringer"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Item Level", "Critical Strike", "Versatility", "Mastery", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Thalassian Diamond" },
        { name = "Flawless Quick Garnet" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Tenacity" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}

-- DEATHKNIGHT Blood [San'layn] | Updated: 2026-04-26
GearPath.GuideData["DEATHKNIGHT"]["Blood"]["San'layn"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Item Level", "Haste", "Critical Strike", "Versatility", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Thalassian Diamond" },
        { name = "Flawless Quick Garnet" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Tenacity" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["DEATHKNIGHT"] = GearPath.GuideData["DEATHKNIGHT"] or {}
GearPath.GuideData["DEATHKNIGHT"]["Frost"] = {}

-- DEATHKNIGHT Frost [any] | Updated: 2026-04-26
GearPath.GuideData["DEATHKNIGHT"]["Frost"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["DEATHKNIGHT"] = GearPath.GuideData["DEATHKNIGHT"] or {}
GearPath.GuideData["DEATHKNIGHT"]["Unholy"] = {}

-- DEATHKNIGHT Unholy [any] | Updated: 2026-04-26
GearPath.GuideData["DEATHKNIGHT"]["Unholy"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
        { slot = "Weapon", enchant = "Enchant Ring - Zul'jin's Mastery due to the high Mastery value" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["DEMONHUNTER"] = GearPath.GuideData["DEMONHUNTER"] or {}
GearPath.GuideData["DEMONHUNTER"]["Devourer"] = {}

-- DEMONHUNTER Devourer [any] | Updated: 2026-04-26
GearPath.GuideData["DEMONHUNTER"]["Devourer"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Mastery", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["DEMONHUNTER"] = GearPath.GuideData["DEMONHUNTER"] or {}
GearPath.GuideData["DEMONHUNTER"]["Havoc"] = {}

-- DEMONHUNTER Havoc [any] | Updated: 2026-04-26
GearPath.GuideData["DEMONHUNTER"]["Havoc"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Critical Strike", "Mastery", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["DEMONHUNTER"] = GearPath.GuideData["DEMONHUNTER"] or {}
GearPath.GuideData["DEMONHUNTER"]["Vengeance"] = {}

-- DEMONHUNTER Vengeance [any] | Updated: 2026-04-26
GearPath.GuideData["DEMONHUNTER"]["Vengeance"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Haste", "Versatility", "Critical Strike", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Thalassian Diamond" },
        { name = "Flawless Deadly Peridot" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["DRUID"] = GearPath.GuideData["DRUID"] or {}
GearPath.GuideData["DRUID"]["Balance"] = {}

-- DRUID Balance [any] | Updated: 2026-04-26
GearPath.GuideData["DRUID"]["Balance"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Critical Strike", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Quick Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Helmet", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Nature's Fury" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["DRUID"] = GearPath.GuideData["DRUID"] or {}
GearPath.GuideData["DRUID"]["Feral"] = {}

-- DRUID Feral [any] | Updated: 2026-04-26
GearPath.GuideData["DRUID"]["Feral"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["DRUID"] = GearPath.GuideData["DRUID"] or {}
GearPath.GuideData["DRUID"]["Guardian"] = {}

-- DRUID Guardian [any] | Updated: 2026-04-26
GearPath.GuideData["DRUID"]["Guardian"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Haste", "Versatility", "Critical Strike", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Versatile Peridot" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Silvermoon Parade",
        potion    = "Draught of Rampant Abandon",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["DRUID"] = GearPath.GuideData["DRUID"] or {}
GearPath.GuideData["DRUID"]["Restoration"] = {}

-- DRUID Restoration [any] | Updated: 2026-04-26
GearPath.GuideData["DRUID"]["Restoration"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Mastery", "Versatility", "Critical Strike",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Stoic Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["EVOKER"] = GearPath.GuideData["EVOKER"] or {}
GearPath.GuideData["EVOKER"]["Augmentation"] = {}

-- EVOKER Augmentation [any] | Updated: 2026-04-26
GearPath.GuideData["EVOKER"]["Augmentation"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Item Level", "Critical Strike", "Haste", "Mastery", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Jan'alai's Precision" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Rings", enchant = "Enchant Ring - Nature's Fury" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["EVOKER"] = GearPath.GuideData["EVOKER"] or {}
GearPath.GuideData["EVOKER"]["Devastation"] = {}

-- EVOKER Devastation [any] | Updated: 2026-04-26
GearPath.GuideData["EVOKER"]["Devastation"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Item Level", "Haste", "Critical Strike", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["EVOKER"] = GearPath.GuideData["EVOKER"] or {}
GearPath.GuideData["EVOKER"]["Preservation"] = {}

-- EVOKER Preservation [any] | Updated: 2026-04-26
GearPath.GuideData["EVOKER"]["Preservation"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Royal Roast",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["HUNTER"] = GearPath.GuideData["HUNTER"] or {}
GearPath.GuideData["HUNTER"]["BeastMastery"] = {}

-- HUNTER BeastMastery [any] | Updated: 2026-04-26
GearPath.GuideData["HUNTER"]["BeastMastery"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["HUNTER"] = GearPath.GuideData["HUNTER"] or {}
GearPath.GuideData["HUNTER"]["Marksmanship"] = {}

-- HUNTER Marksmanship [any] | Updated: 2026-04-26
GearPath.GuideData["HUNTER"]["Marksmanship"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Critical Strike", "Mastery", "Versatility", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["HUNTER"] = GearPath.GuideData["HUNTER"] or {}
GearPath.GuideData["HUNTER"]["Survival"] = {}

-- HUNTER Survival [any] | Updated: 2026-04-26
GearPath.GuideData["HUNTER"]["Survival"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["MAGE"] = GearPath.GuideData["MAGE"] or {}
GearPath.GuideData["MAGE"]["Arcane"] = {}

-- MAGE Arcane [any] | Updated: 2026-04-26
GearPath.GuideData["MAGE"]["Arcane"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Versatility", "Critical Strike", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Versatile Amethyst" },
    },

    Enchants = {
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of Thalassian Resistance",
        food      = "Quel'dorei Medley",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["MAGE"] = GearPath.GuideData["MAGE"] or {}
GearPath.GuideData["MAGE"]["Fire"] = {}

-- MAGE Fire [any] | Updated: 2026-04-26
GearPath.GuideData["MAGE"]["Fire"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Mastery", "Versatility", "Critical Strike",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of Thalassian Resistance",
        food      = "Quel'dorei Medley",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["MAGE"] = GearPath.GuideData["MAGE"] or {}
GearPath.GuideData["MAGE"]["Frost"] = {}

-- MAGE Frost [any] | Updated: 2026-04-26
GearPath.GuideData["MAGE"]["Frost"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Jan'alai's Precision" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["MONK"] = GearPath.GuideData["MONK"] or {}
GearPath.GuideData["MONK"]["Brewmaster"] = {}

-- MONK Brewmaster [any] | Updated: 2026-04-26
GearPath.GuideData["MONK"]["Brewmaster"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Item Level", "Critical Strike", "Versatility", "Mastery", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Lapis" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["MONK"] = GearPath.GuideData["MONK"] or {}
GearPath.GuideData["MONK"]["Mistweaver"] = {}

-- MONK Mistweaver [any] | Updated: 2026-04-26
GearPath.GuideData["MONK"]["Mistweaver"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Critical Strike", "Versatility", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Lapis" },
        { name = "Flawless Deadly Peridot" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["MONK"] = GearPath.GuideData["MONK"] or {}
GearPath.GuideData["MONK"]["Windwalker"] = {}

-- MONK Windwalker [any] | Updated: 2026-04-26
GearPath.GuideData["MONK"]["Windwalker"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Haste", "Critical Strike", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Quick Garnet" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["PALADIN"] = GearPath.GuideData["PALADIN"] or {}
GearPath.GuideData["PALADIN"]["Holy"] = {}

-- PALADIN Holy [HeraldoftheSun] | Updated: 2026-04-26
GearPath.GuideData["PALADIN"]["Holy"]["HeraldoftheSun"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}

-- PALADIN Holy [Lightsmith] | Updated: 2026-04-26
GearPath.GuideData["PALADIN"]["Holy"]["Lightsmith"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}

-- PALADIN Holy [any] | Updated: 2026-04-26
GearPath.GuideData["PALADIN"]["Holy"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "",
    },
}


GearPath.GuideData["PALADIN"] = GearPath.GuideData["PALADIN"] or {}
GearPath.GuideData["PALADIN"]["Protection"] = {}

-- PALADIN Protection [any] | Updated: 2026-04-26
GearPath.GuideData["PALADIN"]["Protection"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Haste", "Versatility", "Mastery", "Critical Strike",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Tenacity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Royal Roast",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["PALADIN"] = GearPath.GuideData["PALADIN"] or {}
GearPath.GuideData["PALADIN"]["Retribution"] = {}

-- PALADIN Retribution [any] | Updated: 2026-04-26
GearPath.GuideData["PALADIN"]["Retribution"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Strength", "Mastery", "Critical Strike", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Royal Roast",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["PRIEST"] = GearPath.GuideData["PRIEST"] or {}
GearPath.GuideData["PRIEST"]["Discipline"] = {}

-- PRIEST Discipline [Oracle] | Updated: 2026-04-26
GearPath.GuideData["PRIEST"]["Discipline"]["Oracle"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Haste", "Critical Strike", "Versatility", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Peridot" },
    },

    Enchants = {
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Royal Roast",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}

-- PRIEST Discipline [Voidweaver] | Updated: 2026-04-26
GearPath.GuideData["PRIEST"]["Discipline"]["Voidweaver"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Haste", "Critical Strike", "Versatility", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Peridot" },
    },

    Enchants = {
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Royal Roast",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["PRIEST"] = GearPath.GuideData["PRIEST"] or {}
GearPath.GuideData["PRIEST"]["Holy"] = {}

-- PRIEST Holy [any] | Updated: 2026-04-26
GearPath.GuideData["PRIEST"]["Holy"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Critical Strike", "Versatility", "Mastery", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching Enchant Helm" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending Enchant Shoulders" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul Enchant Chest" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots Enchant Boots" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle Enchant Ring" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei Enchant Weapon" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["PRIEST"] = GearPath.GuideData["PRIEST"] or {}
GearPath.GuideData["PRIEST"]["Shadow"] = {}

-- PRIEST Shadow [Archon] | Updated: 2026-04-26
GearPath.GuideData["PRIEST"]["Shadow"]["Archon"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Mastery", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Quick Lapis" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Quick Garnet" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Arcane Mastery" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul Enchant Chest" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread Bright Linen Spellthread" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}

-- PRIEST Shadow [Voidweaver] | Updated: 2026-04-26
GearPath.GuideData["PRIEST"]["Shadow"]["Voidweaver"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Mastery", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Quick Lapis" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Quick Garnet" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Arcane Mastery" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul Enchant Chest" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread Bright Linen Spellthread" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["ROGUE"] = GearPath.GuideData["ROGUE"] or {}
GearPath.GuideData["ROGUE"]["Assassination"] = {}

-- ROGUE Assassination [any] | Updated: 2026-04-26
GearPath.GuideData["ROGUE"]["Assassination"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Critical Strike", "Haste", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit." },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Nature's Fury" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["ROGUE"] = GearPath.GuideData["ROGUE"] or {}
GearPath.GuideData["ROGUE"]["Outlaw"] = {}

-- ROGUE Outlaw [any] | Updated: 2026-04-26
GearPath.GuideData["ROGUE"]["Outlaw"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Critical Strike", "Haste", "Versatility", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Jan'alai's Precision" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Nature's Fury" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["ROGUE"] = GearPath.GuideData["ROGUE"] or {}
GearPath.GuideData["ROGUE"]["Subtlety"] = {}

-- ROGUE Subtlety [any] | Updated: 2026-04-26
GearPath.GuideData["ROGUE"]["Subtlety"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Haste", "Critical Strike", "Mastery", "Haste", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Masterful Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Blood Knights",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["SHAMAN"] = GearPath.GuideData["SHAMAN"] or {}
GearPath.GuideData["SHAMAN"]["Elemental"] = {}

-- SHAMAN Elemental [any] | Updated: 2026-04-26
GearPath.GuideData["SHAMAN"]["Elemental"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Arcane Mastery" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["SHAMAN"] = GearPath.GuideData["SHAMAN"] or {}
GearPath.GuideData["SHAMAN"]["Enhancement"] = {}

-- SHAMAN Enhancement [Stormbringer] | Updated: 2026-04-26
GearPath.GuideData["SHAMAN"]["Enhancement"]["Stormbringer"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Mastery", "Haste", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "",
        augRune   = "Void-Touched Augment Rune",
    },
}

-- SHAMAN Enhancement [Totemic] | Updated: 2026-04-26
GearPath.GuideData["SHAMAN"]["Enhancement"]["Totemic"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Agility", "Haste", "Mastery", "Critical Strike", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Off Hand", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Rune of Avoidance" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Amirdrassil's Grace" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Forest Hunter's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Zul'jin's Mastery" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Silvermoon Parade",
        potion    = "Light's Potential",
        weaponOil = "",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["SHAMAN"] = GearPath.GuideData["SHAMAN"] or {}
GearPath.GuideData["SHAMAN"]["Restoration"] = {}

-- SHAMAN Restoration [any] | Updated: 2026-04-26
GearPath.GuideData["SHAMAN"]["Restoration"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Item Level", "Critical Strike", "Versatility", "Mastery", "Haste",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Telluric Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Deadly Peridot" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Legs", enchant = "Arcanoweave Spellthread" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Magister" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
        { slot = "Rings", enchant = "Enchant Ring - Nature's Fury" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Silvermoon Parade",
        potion    = "",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARLOCK"] = GearPath.GuideData["WARLOCK"] or {}
GearPath.GuideData["WARLOCK"]["Affliction"] = {}

-- WARLOCK Affliction [any] | Updated: 2026-04-26
GearPath.GuideData["WARLOCK"]["Affliction"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Haste", "Critical Strike", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Versatile Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Blooming Feast",
        potion    = "Draught of Rampant Abandon",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARLOCK"] = GearPath.GuideData["WARLOCK"] or {}
GearPath.GuideData["WARLOCK"]["Demonology"] = {}

-- WARLOCK Demonology [any] | Updated: 2026-04-26
GearPath.GuideData["WARLOCK"]["Demonology"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Critical Strike", "Haste", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Versatile Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Blooming Feast",
        potion    = "Draught of Rampant Abandon",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARLOCK"] = GearPath.GuideData["WARLOCK"] or {}
GearPath.GuideData["WARLOCK"]["Destruction"] = {}

-- WARLOCK Destruction [any] | Updated: 2026-04-26
GearPath.GuideData["WARLOCK"]["Destruction"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Intellect", "Critical Strike", "Haste", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Powerful Eversong Diamond" },
        { name = "Flawless Deadly Amethyst" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Deadly Lapis" },
        { name = "Flawless Masterful Lapis" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Versatile Peridot" },
        { name = "Flawless Masterful Garnet" },
    },

    Enchants = {
        { slot = "Helm", enchant = "Enchant Helm - Empowered Blessing of Speed" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Sunfire Silk Spellthread" },
        { slot = "Boots", enchant = "Enchant Boots - Farstrider's Hunt" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Blooming Feast",
        potion    = "Draught of Rampant Abandon",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARRIOR"] = GearPath.GuideData["WARRIOR"] or {}
GearPath.GuideData["WARRIOR"]["Arms"] = {}

-- WARRIOR Arms [any] | Updated: 2026-04-26
GearPath.GuideData["WARRIOR"]["Arms"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Strength", "Critical Strike", "Haste", "Mastery", "Versatility",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Quick Garnet" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Berserker's Rage" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARRIOR"] = GearPath.GuideData["WARRIOR"] or {}
GearPath.GuideData["WARRIOR"]["Fury"] = {}

-- WARRIOR Fury [any] | Updated: 2026-04-26
GearPath.GuideData["WARRIOR"]["Fury"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Strength", "Mastery", "Haste", "Versatility", "Critical Strike",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Quick Amethyst" },
        { name = "Flawless Masterful Peridot" },
    },

    Enchants = {
        { slot = "Weapon", enchant = "Enchant Weapon - Arcane Mastery" },
        { slot = "Helm", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Lynx's Dexterity" },
        { slot = "Rings", enchant = "Enchant Ring - Eyes of the Eagle" },
    },

    Consumables = {
        flask     = "Flask of the Magisters",
        food      = "Harandar Celebration",
        potion    = "Potion of Recklessness",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}


GearPath.GuideData["WARRIOR"] = GearPath.GuideData["WARRIOR"] or {}
GearPath.GuideData["WARRIOR"]["Protection"] = {}

-- WARRIOR Protection [any] | Updated: 2026-04-26
GearPath.GuideData["WARRIOR"]["Protection"]["any"] = {

    Stats = {
        format  = "ordered",
        ordered = { "Strength", "Item Level", "Haste", "Versatility", "Critical Strike", "Mastery",  },
    },

    Gems = {
        { name = "Indecipherable Eversong Diamond" },
        { name = "Flawless Deadly Peridot" },
        { name = "Flawless Versatile Peridot" },
    },

    Enchants = {
        { slot = "Rings", enchant = "Enchant Ring - Silvermoon's Alacrity" },
        { slot = "Weapon", enchant = "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot = "Helmet", enchant = "Enchant Helm - Empowered Hex of Leeching" },
        { slot = "Shoulders", enchant = "Enchant Shoulders - Silvermoon's Mending" },
        { slot = "Chest", enchant = "Enchant Chest - Mark of the Worldsoul" },
        { slot = "Legs", enchant = "Blood Knight's Armor Kit" },
        { slot = "Boots", enchant = "Enchant Boots - Shaladrassil's Roots" },
    },

    Consumables = {
        flask     = "Flask of the Shattered Sun",
        food      = "Harandar Celebration",
        potion    = "Light's Potential",
        weaponOil = "Thalassian Phoenix Oil",
        augRune   = "Void-Touched Augment Rune",
    },
}

